### ISSUE TITLE
Expand secure memory on 4.4.0 failed

### ISSUE THREAD

**Issue by YogzZ** [TephrocactusMYC/llama2-optee#1]
Hi, I am trying to expand the secure memory on OP-TEE 4.4.0 with your changes, but get `Invalid Device Tree at 0x48000000: error -9` in `init_external_dt`.

Do you have any ideas to solve the problem?

**Comment by TephrocactusMYC** [comment]
@YogzZ I'm sorry, but I am not responsible for maintaining this project and don't have the ability to answer your questions. You can try opening an issue in [the official OP-TEE repository](https://github.com/OP-TEE/optee_os) to seek help.

**Comment by TephrocactusMYC** [comment]
@YogzZ 

Recently, my friend also tried using this method on version 4.4.0 and encountered the same problem. I believe solving this problem requires **debugging**. The screenshots my friend sent me show that a good function call stack can be obtained. This is the quickest and simplest approach. 

Additionally, the device tree issue is actually caused by me moving the address of a block of memory. Therefore, you need to update all the addresses related to this memory in subprojects like OP-TEE, TF-A, U-BOOT, etc., to the new address. The current issue might be that some changes were missed in certain places due to software engineering reasons, such as macro definitions or other constants not being updated. In any case, solving this problem isn't difficult, though it might be a bit tedious.

**Comment by YogzZ** [comment]
@TephrocactusMYC Thank you for your advice.

I will comment this issue if I solve the problem.

**Comment by TephrocactusMYC** [comment]
> @TephrocactusMYC Thank you for your advice.
> 
> I will comment this issue if I solve the problem.

Alright, I wish you all the best. 

If you're unable to resolve the issue, this project is currently in the handover process, and a new maintainer will take over within the next three months at the latest. Perhaps he/she will be able to solve your problem.

**Comment by YogzZ** [comment]
Hi, I am using your patch successfully on 4.4.0 with the following steps:
1. get all the projects with 4.2.0 manifest.
2. update `optee_os` `optee_client` `optee_example` `optee_test` `build`  to 4.4.0.
3. update your patches.

But I cannot expand the TEE RAM more than 0x8000000.

Hope someone can leave a comment if they've found a solution to this problem.

**Comment by TephrocactusMYC** [comment]
> Hi, I am using your patch successfully on 4.4.0 with the following steps:
> 
> 1. get all the projects with 4.2.0 manifest.
> 2. update `optee_os` `optee_client` `optee_example` `optee_test` `build`  to 4.4.0.
> 3. update your patches.

This is really good news! Thank you for the update!

> But I cannot expand the TEE RAM more than 0x8000000.
> 
> Hope someone can leave a comment if they've found a solution to this problem.

Regarding your question, I still recommend you ask in the official repository. My repository doesn't have many followers, and I'm afraid you might not get a response here.
